# -*- coding: utf-8 -*-
"""VJEPA-Hackahton.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15UTfipKt865b7b4rtRbxQsJyKiWQU_Hd
"""

import torch
import os
import torch.nn as nn
from transformers import AutoVideoProcessor, AutoModel
import easyocr
import re

hf_repo = "facebook/vjepa2-vitl-fpc64-256"
# facebook/vjepa2-vitl-fpc64-256
# facebook/vjepa2-vith-fpc64-256
# facebook/vjepa2-vitg-fpc64-256
# facebook/vjepa2-vitg-fpc64-384


model = AutoModel.from_pretrained(hf_repo)
processor = AutoVideoProcessor.from_pretrained(hf_repo)

model.eval()
model.to("cuda")
print('done')

reader = easyocr.Reader(['en'], gpu=True)

class CompressionClassifier(nn.Module):
    def __init__(self, num_classes=2):
        super().__init__()
        repo = "facebook/vjepa2-vitl-fpc64-256"
        self.encoder = model
        self.processor = processor

        for param in self.encoder.parameters():
            param.requires_grad = False

        self.head = nn.Sequential(
            nn.Linear(1024, 256),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(256, num_classes)
        ).to("cuda")

    def forward(self, frames):
        inputs = self.processor(videos=frames, return_tensors="pt")
        inputs = {k: v.to(next(self.parameters()).device) for k, v in inputs.items()}

        with torch.no_grad():
            emb = self.encoder(**inputs).last_hidden_state.mean(dim=1)

        return self.head(emb)

import cv2 as cv
import numpy as np
from PIL import Image
def video_to_PIL(video, start_frame=0, end_frame=None, max_frames=64):
    frames = []
    cap = cv.VideoCapture(video)
    cap.set(cv.CAP_PROP_POS_FRAMES, start_frame)

    frame_idx = start_frame
    while True:
        ret, frame = cap.read()
        if not ret or (end_frame and frame_idx >= end_frame):
            break
        frames.append(Image.fromarray(cv.cvtColor(frame, cv.COLOR_BGR2RGB)))
        frame_idx += 1
        if len(frames) >= max_frames:
            break

    cap.release()
    return frames

from torch.utils.data import random_split, DataLoader, Dataset
import pandas as pd
class CustomVideoDataset(Dataset):
    def __init__(self, annotations_file, video_dir):
        # Build a flat list of (video_path, start_frame, end_frame, label)
        self.samples = []
        for csv_path, video_path in zip(annotations_file, video_dir):
            df = pd.read_csv(csv_path, skiprows=2)
            df.columns = ["compression_num", "start_frame", "end_frame"]
            compression_ranges = list(zip(df["start_frame"], df["end_frame"]))

            # Get total frame count to sample non-compression clips
            cap = cv.VideoCapture(video_path)
            total_frames = int(cap.get(cv.CAP_PROP_FRAME_COUNT))
            cap.release()

            # Positive samples (compression)
            for start, end in compression_ranges:
                self.samples.append((video_path, start, end, 1))

            # Negative samples (non-compression) — gaps between compressions
            prev_end = 0
            for start, end in compression_ranges:
                if start - prev_end > 10:  # ignore tiny gaps
                    self.samples.append((video_path, prev_end, start, 0))
                prev_end = end
            if total_frames - prev_end > 10:
                self.samples.append((video_path, prev_end, total_frames, 0))

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        video_path, start, end, label = self.samples[idx]
        frames = video_to_PIL(video_path, start, end)
        return frames, label

save_path = '/content/drive/MyDrive/model_weights/my_model_weights'

def train(model, dataset, epochs=10, lr=0.001):
    model.train()
    optimizer = torch.optim.Adam(model.head.parameters(), lr=lr)
    loss_fn = nn.CrossEntropyLoss()

    for epoch in range(epochs):
        total_loss = 0
        correct = 0

        for i in range(len(dataset)):
            frames, label = dataset[i]

            optimizer.zero_grad()
            output = model(frames)
            target = torch.tensor([label]).to(output.device)

            loss = loss_fn(output, target)
            loss.backward()
            optimizer.step()

            total_loss += loss.item()
            correct += (output.argmax(1) == target).sum().item()
            torch.cuda.empty_cache()

        acc = correct / len(dataset)
        print(f"Epoch {epoch+1}/{epochs} | Loss: {total_loss/len(dataset):.4f} | Acc: {acc:.2%}")
        torch.save(model.state_dict(), save_path + str(epoch) + '.pth')


    return model

def evaluate(model, dataset):
    model.eval()
    correct = 0
    with torch.no_grad():
        for i in range(len(dataset)):
            frames, label = dataset[i]
            output = model(frames)
            target = torch.tensor([label]).to(output.device)
            correct += (output.argmax(1) == target).sum().item()
    print(f"Test Acc: {correct / len(dataset):.2%}")

Grooming_States = ['non-compression','compression']
#ask tomorrow about specifics

from google.colab import drive
drive.mount('/content/drive')

def load_videos(path_name_os):
  annotations_file = []
  video_name_file = []
  for dirname, _, filenames in os.walk(path_name_os):
        print(dirname)
        for filename in filenames:
            if "run_" in filename:
              if "csv" in filename:
                annotations_file.append( os.path.join(dirname, filename))
              if "mp4" in filename:
                video_name_file.append( os.path.join(dirname, filename))
  annotations_file.sort()
  video_name_file.sort()
  return annotations_file, video_name_file

import numpy as np
import polars as pl
#annotations_file = np.read_csv('')
#video_name_file = np.read_csv('')
#for i in len(video_name_file):
#cap = cv.VideoCapture(i)
#run_8_patient_2

annotations_file, video_name_file = load_videos('/content/drive/MyDrive/annotation_videos_correct')

video_dataset = CustomVideoDataset(annotations_file,video_name_file)

total_len = len(video_dataset)
train_len = int(total_len * 0.9)
test_len = total_len - train_len

from sklearn.model_selection import train_test_split
train_dataset, test_dataset = random_split(
    video_dataset,
    [train_len, test_len],
    generator=torch.Generator().manual_seed(42)
)

#compression_analysis = CompressionClassifier()

#train(compression_analysis, train_dataset)

#evaluate(compression_analysis, test_dataset)

#test_annotation_file, test_video_name_file = load_videos('/content/drive/MyDrive/test_videos')

#weights_path = '/content/drive/MyDrive/model_weights/my_model_weights3.pth'
#compression_analysis = CompressionClassifier() # Instantiate your custom CompressionClassifier
#compression_analysis.load_state_dict(torch.load(weights_path))
#compression_analysis.eval()



#compression_analysis